### ISSUE TITLE
[Enhancement] Show the muted tab icon alongside the favicon.

### ISSUE THREAD

**Issue by xplshn** [rockofox/firefox-minima#13]
Or otherwise make it be easily discernible, even at smaller than default tab heights

**Comment by rockofox** [comment]
Added, thanks for your idea!

https://github.com/rockofox/firefox-minima/commit/478e677f8fc2c15e86c6ff2e5af2a8bfce313f7e

**Comment by xplshn** [comment]
Great! Thanks! This is awesome!
![2024-02-15-171057_1366x768_scrot](https://github.com/rockofox/firefox-minima/assets/114888778/a370d615-103d-4d81-818a-62e5c9a2c301)
