### ISSUE TITLE
Media Playing notification in tab adds a second line

### ISSUE THREAD

**Issue by JBlocklove** [rockofox/firefox-minima#5]
I just updated to the most recent version of this to work with Firefox's current version and now when I'm playing media (I've tested with both YouTube and Jellyfin) the little playing notification shows up and shifts the text in the tab up weirdly. I don't remember what this looked like before I updated but I don't remember it looking like this. Any idea what needs to be changed to fix this, other than making the tabs super tall?

![1671224838](https://user-images.githubusercontent.com/24708457/208189741-93ab71f7-968e-4859-87d1-2d18217cf0b4.png)

**Comment by rockofox** [comment]
Interesting, this issue didn't occur to me yet, as I was still using the (now unsupported) compact UI density. But I switched away from it now, as it surely will be removed at some point. This made me able to reproduce the bug and push out a quick fix.

Anyway, it should be fixed now, feel free to reopen the issue if it still occurs for you after updating.

**Comment by JBlocklove** [comment]
Fixed it perfectly, thanks for the quick fix!
