### ISSUE TITLE
Invisible Tab Bar

### ISSUE THREAD

**Issue by nfn8** [rockofox/firefox-minima#6]
Hello, 

After FF 108 update I received the invisible tab bar error. I would say it is more of a privacy shade if I am looking at the silver lining. I can still hover over the invisible tab bar to know which tab is which but it is taxing my productivity.  I tried removing #tabbrowser-arrowscrollbox{ min-height: 0 !important; } and restarting but with no luck. Would you know a fix for this?

My userChrome.css only has the minima config code. Thank you very much for the theme. 

![FFMinimatheme-invisibletabs](https://user-images.githubusercontent.com/16066493/208248749-bde08487-d1ac-4d95-8fee-062e693af3b3.png)

**Comment by rockofox** [comment]
Hm, I kinda have problems reproducing this issue.
What OS do you use? Maybe that can help to find the issue
