### ISSUE TITLE
Inappropiate tab size on new Firefox version

### ISSUE THREAD

**Issue by MiliAxe** [rockofox/firefox-minima#9]
Just like always. another beta, another userChrome issue!

after upgrading to Firefox developer edition 118.0b6 I have noticed that the size of tabs have gotten inappropriately larger. 

![image](https://github.com/rockofox/firefox-minima/assets/55515322/c267e4e9-5a92-4b53-be40-2a8a2c07b192)

Thanks for the great userChrome!

**Comment by rockofox** [comment]
Do you have the newest version? I recently fixed something like this in 932a998.
I'll still take a look, my solution might not be optimal and might not work properly depending on factors like tab size, etc.

Thanks for the praise! It's always great to hear about happy users ;)

**Comment by MiliAxe** [comment]
I'm so sorry, after a few restarts. I can't reproduce that issue anymore. I guess it was a temporary issue? Sorry for the inconvenience.

**Comment by nnzv** [comment]
After updating to LibreWolf `118.0.2-1`, I began encountering this issue. In the past, I didn't face any problems with earlier LibreWolf versions. The problem got fixed when I updated the Chrome CSS, which was outdated. Thanks for your help!
